"""Unified observation layout description. Single source of truth for parsing.

Generated by ObservationBuilder; consumed by StructuredActorNetwork and TICA.
Eliminates hand-rolled pointer arithmetic that caused the beliefs-geometry
interleaving bug (P0-0, 2026-07-17).
"""
from dataclasses import dataclass
from typing import Optional
import numpy as np


@dataclass(frozen=True)
class ObservationSlices:
    """Immutable slice descriptors for flat observation vector.

    Layout (with rel_features=True, use_p0_global_info=False):
        self(8) | beliefs(Q*9) | geometry(Q*8) | physics(3) |
        neighbors((K-1)*neighbor_dim) | global(2) | PD_hist(Q) | comm(16)

    With P0: coverage(Q) + pairing(K-1) inserted before neighbors;
    global becomes non-zero. neighbor_dim = 9 (with in_pair) or 8 (without).
    """
    self_start: int = 0
    self_len: int = 8

    belief_start: int = 8
    belief_per_target: int = 9  # mean(4) + cov(4) + aoi(1)

    # Set after beliefs
    geom_start: int = 0
    geom_per_target: int = 8  # dx,dy,dist,sin,cos,d_s1,d_s2,d_s3

    physics_start: int = 0
    physics_len: int = 3

    coverage_start: int = 0
    coverage_len: int = 0  # set from Q if has_p0

    pairing_start: int = 0
    pairing_len: int = 0  # set from K-1 if has_p0

    neighbor_start: int = 0
    neighbor_per_agent: int = 8  # 8 without P0, 9 with

    global_start: int = 0
    global_len: int = 2

    pd_hist_start: int = 0
    pd_hist_len: int = 0  # set from Q

    comm_start: int = 0
    comm_len: int = 16

    # Derived
    K: int = 4
    Q: int = 4
    has_p0: bool = False
    has_rel_features: bool = True

    @staticmethod
    def from_config(K: int, Q: int, use_p0: bool = False,
                    use_rel_features: bool = True) -> "ObservationSlices":
        """Build slice descriptors from scenario config."""
        s = ObservationSlices(K=K, Q=Q, has_p0=use_p0,
                              has_rel_features=use_rel_features)

        # Beliefs block
        belief_len = Q * s.belief_per_target
        belief_end = s.self_start + s.self_len + belief_len

        # Geometry block (only if rel_features)
        if use_rel_features:
            geom_start = belief_end
            geom_len = Q * s.geom_per_target
            geom_end = geom_start + geom_len
        else:
            geom_start = belief_end
            geom_len = 0
            geom_end = belief_end

        # Physics
        phys_end = geom_end + s.physics_len

        # P0 info
        cov_start = phys_end
        cov_len = Q if use_p0 else 0
        cov_end = cov_start + cov_len

        pair_start = cov_end
        pair_len = (K - 1) if use_p0 else 0
        pair_end = pair_start + pair_len

        # Neighbors
        neighbor_dim = 9 if use_p0 else 8
        neighbor_len = (K - 1) * neighbor_dim
        neighbor_end = pair_end + neighbor_len

        # Global (only with P0)
        global_len = s.global_len if use_p0 else 0
        global_end = neighbor_end + global_len

        # PD_hist
        pd_hist_end = global_end + Q

        # Comm
        comm_end = pd_hist_end + s.comm_len

        return ObservationSlices(
            K=K, Q=Q, has_p0=use_p0, has_rel_features=use_rel_features,
            self_start=0, self_len=8,
            belief_start=8, belief_per_target=9,
            geom_start=geom_start, geom_per_target=8,
            physics_start=geom_end, physics_len=3,
            coverage_start=cov_start, coverage_len=cov_len,
            pairing_start=pair_start, pairing_len=pair_len,
            neighbor_start=pair_end, neighbor_per_agent=neighbor_dim,
            global_start=neighbor_end, global_len=global_len,
            pd_hist_start=global_end, pd_hist_len=Q,
            comm_start=pd_hist_end, comm_len=16,
        )

    @property
    def total_dim(self) -> int:
        return self.comm_start + self.comm_len

    def extract_self(self, obs: np.ndarray):
        return obs[..., self.self_start:self.self_start + self.self_len]

    def extract_beliefs(self, obs: np.ndarray):
        """Returns (..., Q, 9) beliefs array."""
        L = self.Q * self.belief_per_target
        raw = obs[..., self.belief_start:self.belief_start + L]
        return raw.reshape(*raw.shape[:-1], self.Q, self.belief_per_target)

    def extract_geometry(self, obs: np.ndarray):
        """Returns (..., Q, 8) geometry array, or None if not rel_features."""
        if not self.has_rel_features or self.geom_per_target == 0:
            return None
        L = self.Q * self.geom_per_target
        raw = obs[..., self.geom_start:self.geom_start + L]
        return raw.reshape(*raw.shape[:-1], self.Q, self.geom_per_target)

    def extract_physics(self, obs: np.ndarray):
        return obs[..., self.physics_start:self.physics_start + self.physics_len]

    def extract_pd_hist(self, obs: np.ndarray):
        return obs[..., self.pd_hist_start:self.pd_hist_start + self.pd_hist_len]

    def extract_comm(self, obs: np.ndarray):
        return obs[..., self.comm_start:self.comm_start + self.comm_len]

    def extract_neighbors(self, obs: np.ndarray):
        """Returns (..., K-1, neighbor_dim) neighbors array."""
        L = (self.K - 1) * self.neighbor_per_agent
        raw = obs[..., self.neighbor_start:self.neighbor_start + L]
        return raw.reshape(*raw.shape[:-1], self.K - 1, self.neighbor_per_agent)
