#!/usr/bin/env python
"""Target-wise causal token-value probe with uncertainty-aware gating.

Consumes paired-intervention datasets generated by
``probe_causal_token_value.py``.  It predicts the token-induced P_D change for
every target, the no-token worst-target identity, and whether the worst identity
will switch.  All train-time gate scores are out-of-fold by episode seed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Iterable, Tuple

import numpy as np


def load_dataset(path: str) -> Dict[str, np.ndarray]:
    with np.load(path) as data:
        required = {
            "protocol", "local", "central", "delta_pd", "delta_qos",
            "drop_worst_id", "send_worst_id", "episode_seed",
        }
        missing = required - set(data.files)
        if missing:
            raise ValueError(
                "dataset predates target-wise causal labels; regenerate it: "
                f"{sorted(missing)}")
        return {name: np.asarray(data[name]) for name in data.files}


def rank_correlation(y: np.ndarray, prediction: np.ndarray) -> float:
    from scipy.stats import spearmanr

    y = np.asarray(y).reshape(-1)
    prediction = np.asarray(prediction).reshape(-1)
    if np.unique(y).size < 2 or np.unique(prediction).size < 2:
        return 0.0
    value = spearmanr(y, prediction).statistic
    return float(value) if np.isfinite(value) else 0.0


def make_regressor(seed: int, trees: int):
    from sklearn.ensemble import ExtraTreesRegressor

    return ExtraTreesRegressor(
        n_estimators=int(trees),
        min_samples_leaf=3,
        max_features=0.5,
        bootstrap=True,
        max_samples=0.85,
        random_state=int(seed),
        n_jobs=-1,
    )


def make_classifier(seed: int, trees: int):
    from sklearn.ensemble import ExtraTreesClassifier

    return ExtraTreesClassifier(
        n_estimators=int(trees),
        min_samples_leaf=3,
        max_features=0.5,
        bootstrap=True,
        max_samples=0.85,
        class_weight="balanced",
        random_state=int(seed),
        n_jobs=-1,
    )


def tree_regression_distribution(model, x: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    predictions = np.stack([
        estimator.predict(x) for estimator in model.estimators_
    ], axis=0)
    return predictions.mean(axis=0), predictions.std(axis=0)


def aligned_probabilities(model, x: np.ndarray, q_count: int) -> np.ndarray:
    raw = model.predict_proba(x)
    result = np.zeros((x.shape[0], q_count), dtype=np.float64)
    for index, label in enumerate(model.classes_.astype(np.int64)):
        if 0 <= label < q_count:
            result[:, label] = raw[:, index]
    normalizer = result.sum(axis=1, keepdims=True)
    missing = normalizer[:, 0] <= 1e-12
    result[missing] = 1.0 / max(q_count, 1)
    result[~missing] /= normalizer[~missing]
    return result


def episode_folds(groups: np.ndarray) -> Iterable[Tuple[np.ndarray, np.ndarray]]:
    unique = np.unique(groups)
    if unique.size < 2:
        raise ValueError("target-wise probe needs at least two training episodes")
    for held_out in unique:
        validation = groups == held_out
        yield ~validation, validation


def out_of_fold_predictions(
    x: np.ndarray,
    delta_pd: np.ndarray,
    worst_id: np.ndarray,
    worst_changed: np.ndarray,
    groups: np.ndarray,
    seed: int,
    trees: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    q_count = delta_pd.shape[1]
    effect = np.zeros_like(delta_pd, dtype=np.float64)
    uncertainty = np.zeros_like(delta_pd, dtype=np.float64)
    worst_probability = np.zeros_like(delta_pd, dtype=np.float64)
    switch_probability = np.zeros(x.shape[0], dtype=np.float64)
    for fold, (train_index, validation_index) in enumerate(
            episode_folds(groups)):
        regressor = make_regressor(seed + fold, trees)
        regressor.fit(x[train_index], delta_pd[train_index])
        mean, std = tree_regression_distribution(
            regressor, x[validation_index])
        effect[validation_index] = mean
        uncertainty[validation_index] = std

        classifier = make_classifier(seed + 101 + fold, trees)
        classifier.fit(x[train_index], worst_id[train_index])
        worst_probability[validation_index] = aligned_probabilities(
            classifier, x[validation_index], q_count)

        switch_model = make_classifier(seed + 211 + fold, trees)
        switch_model.fit(x[train_index], worst_changed[train_index])
        if switch_model.classes_.size == 1:
            switch_probability[validation_index] = float(
                switch_model.classes_[0])
        else:
            positive_column = int(np.flatnonzero(
                switch_model.classes_.astype(np.int64) == 1)[0])
            switch_probability[validation_index] = switch_model.predict_proba(
                x[validation_index])[:, positive_column]
    return effect, uncertainty, worst_probability, switch_probability


def fit_full_models(
    x_train: np.ndarray,
    x_test: np.ndarray,
    delta_pd: np.ndarray,
    worst_id: np.ndarray,
    worst_changed: np.ndarray,
    seed: int,
    trees: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    q_count = delta_pd.shape[1]
    regressor = make_regressor(seed, trees)
    regressor.fit(x_train, delta_pd)
    effect, uncertainty = tree_regression_distribution(regressor, x_test)

    classifier = make_classifier(seed + 101, trees)
    classifier.fit(x_train, worst_id)
    worst_probability = aligned_probabilities(classifier, x_test, q_count)

    switch_model = make_classifier(seed + 211, trees)
    switch_model.fit(x_train, worst_changed)
    if switch_model.classes_.size == 1:
        switch_probability = np.full(
            x_test.shape[0], float(switch_model.classes_[0]))
    else:
        positive_column = int(np.flatnonzero(
            switch_model.classes_.astype(np.int64) == 1)[0])
        switch_probability = switch_model.predict_proba(
            x_test)[:, positive_column]
    return effect, uncertainty, worst_probability, switch_probability


def safe_auc(label: np.ndarray, score: np.ndarray):
    from sklearn.metrics import roc_auc_score

    if np.unique(label).size < 2:
        return None
    return float(roc_auc_score(label, score))


def select_conservative_gate(
    effect: np.ndarray,
    uncertainty: np.ndarray,
    worst_probability: np.ndarray,
    actual_delta_qos: np.ndarray,
    actual_worst_repair: np.ndarray,
    critical_recall_floor: float,
) -> dict:
    candidates = []
    fallback = []
    for kappa in (0.0, 0.25, 0.5, 1.0, 1.5, 2.0):
        score = np.sum(
            worst_probability * (effect - kappa * uncertainty), axis=1)
        thresholds = np.unique(np.quantile(
            score, np.linspace(0.0, 1.0, 101)))
        for threshold in thresholds:
            gate = score > threshold
            recall = (
                float(np.mean(gate[actual_worst_repair]))
                if np.any(actual_worst_repair) else 1.0)
            gain = float(np.mean(actual_delta_qos * gate))
            candidate = (gain, recall, -float(np.mean(gate)), -kappa,
                         -float(threshold))
            fallback.append(candidate)
            if recall >= critical_recall_floor:
                candidates.append(candidate)
    best = max(candidates if candidates else fallback)
    return {
        "gain": float(best[0]),
        "critical_recall": float(best[1]),
        "activation_rate": float(-best[2]),
        "kappa": float(-best[3]),
        "threshold": float(-best[4]),
        "recall_constraint_satisfied": bool(candidates),
    }


def evaluate_view(
    name: str,
    train: Dict[str, np.ndarray],
    test: Dict[str, np.ndarray],
    seed: int,
    trees: int,
    effect_epsilon: float,
    critical_recall_floor: float,
) -> dict:
    from sklearn.metrics import accuracy_score, mean_absolute_error, r2_score

    x_train = np.asarray(train[name], dtype=np.float64)
    x_test = np.asarray(test[name], dtype=np.float64)
    train_delta = np.asarray(train["delta_pd"], dtype=np.float64)
    test_delta = np.asarray(test["delta_pd"], dtype=np.float64)
    q_count = train_delta.shape[1]
    train_worst = train["drop_worst_id"].astype(np.int64)
    test_worst = test["drop_worst_id"].astype(np.int64)
    train_changed = (
        train["send_worst_id"] != train["drop_worst_id"]).astype(np.int64)
    test_changed = (
        test["send_worst_id"] != test["drop_worst_id"]).astype(np.int64)

    (oof_effect, oof_uncertainty, oof_worst_probability,
     oof_switch_probability) = out_of_fold_predictions(
        x_train, train_delta, train_worst, train_changed,
        train["episode_seed"], seed, max(100, trees // 2))
    (test_effect, test_uncertainty, test_worst_probability,
     test_switch_probability) = fit_full_models(
        x_train, x_test, train_delta, train_worst, train_changed,
        seed, trees)

    train_actual_worst_effect = train_delta[
        np.arange(train_delta.shape[0]), train_worst]
    test_actual_worst_effect = test_delta[
        np.arange(test_delta.shape[0]), test_worst]
    train_repair = train_actual_worst_effect > effect_epsilon
    test_repair = test_actual_worst_effect > effect_epsilon
    gate_config = select_conservative_gate(
        oof_effect,
        oof_uncertainty,
        oof_worst_probability,
        train["delta_qos"],
        train_repair,
        critical_recall_floor,
    )
    test_score = np.sum(
        test_worst_probability
        * (test_effect - gate_config["kappa"] * test_uncertainty),
        axis=1,
    )
    test_gate = test_score > gate_config["threshold"]
    oracle_gain = float(np.mean(np.maximum(test["delta_qos"], 0.0)))
    gate_gain = float(np.mean(test["delta_qos"] * test_gate))

    predicted_worst = np.argmax(test_worst_probability, axis=1)
    top2_worst = np.argsort(-test_worst_probability, axis=1)[:, :2]
    top2_accuracy = float(np.mean([
        test_worst[row] in top2_worst[row]
        for row in range(test_worst.size)
    ]))
    sign_label = (test_delta.reshape(-1) > effect_epsilon).astype(np.int64)
    sign_score = test_effect.reshape(-1)
    uncertainty_error_corr = rank_correlation(
        np.abs(test_delta - test_effect), test_uncertainty)
    return {
        "target_effect": {
            "mae": float(mean_absolute_error(
                test_delta.reshape(-1), test_effect.reshape(-1))),
            "r2": float(r2_score(
                test_delta.reshape(-1), test_effect.reshape(-1))),
            "spearman": rank_correlation(test_delta, test_effect),
            "sign_auc": safe_auc(sign_label, sign_score),
            "mean_abs_effect": float(np.mean(np.abs(test_delta))),
            "uncertainty_error_spearman": uncertainty_error_corr,
        },
        "worst_identity": {
            "accuracy": float(accuracy_score(test_worst, predicted_worst)),
            "top2_accuracy": top2_accuracy,
            "switch_rate": float(np.mean(test_changed)),
            "switch_auc": safe_auc(test_changed, test_switch_probability),
        },
        "worst_repair": {
            "positive_rate": float(np.mean(test_repair)),
            "score_auc": safe_auc(test_repair, test_score),
            "critical_recall": (
                float(np.mean(test_gate[test_repair]))
                if np.any(test_repair) else None),
        },
        "gate": {
            "kappa_from_oof_train": gate_config["kappa"],
            "threshold_from_oof_train": gate_config["threshold"],
            "train_recall_constraint_satisfied": (
                gate_config["recall_constraint_satisfied"]),
            "activation_rate": float(np.mean(test_gate)),
            "gain_vs_always_drop": gate_gain,
            "always_send_gain_vs_drop": float(np.mean(test["delta_qos"])),
            "hindsight_oracle_gain_vs_drop": oracle_gain,
            "recovered_oracle_fraction": (
                float(gate_gain / oracle_gain)
                if oracle_gain > 1e-12 else None),
        },
    }


def build_verdict(results: Dict[str, dict]) -> dict:
    local = results["local"]
    effect = local["target_effect"]
    identity = local["worst_identity"]
    repair = local["worst_repair"]
    gate = local["gate"]
    passed = bool(
        effect["sign_auc"] is not None
        and effect["sign_auc"] >= 0.65
        and effect["spearman"] >= 0.20
        and identity["top2_accuracy"] >= 0.70
        and repair["critical_recall"] is not None
        and repair["critical_recall"] >= 0.75
        and gate["recovered_oracle_fraction"] is not None
        and gate["recovered_oracle_fraction"] >= 0.50
        and gate["gain_vs_always_drop"] > 0.0)
    return {
        "verdict": (
            "targetwise_teacher_is_promising"
            if passed else
            "stop_causal_value_gate_route"
        ),
        "predeclared_gates": {
            "target_effect_sign_auc_min": 0.65,
            "target_effect_spearman_min": 0.20,
            "worst_identity_top2_accuracy_min": 0.70,
            "critical_recall_min": 0.75,
            "recovered_oracle_fraction_min": 0.50,
            "gate_gain_must_be_positive": True,
        },
        "local_observed": {
            "target_effect_sign_auc": effect["sign_auc"],
            "target_effect_spearman": effect["spearman"],
            "worst_identity_top2_accuracy": identity["top2_accuracy"],
            "critical_recall": repair["critical_recall"],
            "recovered_oracle_fraction": gate["recovered_oracle_fraction"],
            "gate_gain_vs_always_drop": gate["gain_vs_always_drop"],
        },
        "note": (
            "Failure means the value gate is not integrated; it does not "
            "alter the frozen deployed checkpoint."),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Target-wise uncertainty-aware causal token probe")
    parser.add_argument(
        "--train-data",
        default="results/causal_token_value_probe/datasets_targetwise_h2/train.npz")
    parser.add_argument(
        "--test-data",
        default="results/causal_token_value_probe/datasets_targetwise_h2/test.npz")
    parser.add_argument("--trees", type=int, default=500)
    parser.add_argument("--effect-epsilon", type=float, default=1e-4)
    parser.add_argument("--critical-recall-floor", type=float, default=0.75)
    parser.add_argument("--seed", type=int, default=20260722)
    parser.add_argument(
        "--output",
        default="results/causal_token_value_probe/targetwise_h2.json")
    args = parser.parse_args()

    train = load_dataset(args.train_data)
    test = load_dataset(args.test_data)
    overlap = set(train["episode_seed"].tolist()) & set(
        test["episode_seed"].tolist())
    if overlap:
        raise ValueError(f"train/test episodes overlap: {sorted(overlap)}")
    results = {
        view: evaluate_view(
            view, train, test, args.seed, args.trees,
            args.effect_epsilon, args.critical_recall_floor)
        for view in ("protocol", "local", "central")
    }
    verdict = build_verdict(results)
    report = {
        "schema_version": 1,
        "train_data": args.train_data,
        "test_data": args.test_data,
        "train_rows": int(train["delta_qos"].size),
        "test_rows": int(test["delta_qos"].size),
        "train_seeds": np.unique(train["episode_seed"]).astype(int).tolist(),
        "test_seeds": np.unique(test["episode_seed"]).astype(int).tolist(),
        "model": {
            "family": "episode-OOF ExtraTrees multi-output ensemble",
            "trees": int(args.trees),
            "effect_epsilon": float(args.effect_epsilon),
            "uncertainty": "standard deviation across ensemble trees",
        },
        "results": results,
        "verdict": verdict,
    }
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(verdict, indent=2, ensure_ascii=False))
    print(f"[targetwise-causal] report={output}")


if __name__ == "__main__":
    main()
